spring.main.allow-bean-definition-overriding: true
server.port: 8086

spring:
  application:
    name: payment-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  batch:
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  profiles:
    active: dev

zeebe:
  client:
    security:
      plaintext: true
    broker:
      contact-point: 127.0.0.1:26500
