spring.profiles.active: develop
spring.main.allow-bean-definition-overriding: true

server.port: 8080
spring:
  application:
    name: product-catalog
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  batch:
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true